### ISSUE TITLE
Definir objetivo da classe com mais clareza

### ISSUE THREAD

**Issue by joacir** [Matheusmelo3535/Estudos_TDD#1]
- definir como entidade (getter/setter de atributos, acessibilidade, espelhamento dos atributos da tabela)
- definir como conjunto (CRUD, validações, persistencia no database)

**Comment by Matheusmelo3535** [comment]
Corrigido,  deixei o lutador apenas como representação e criei uma nova classe para ser o conjunto(CrudLutador).
