### ISSUE TITLE
Sempre definir variaveis para os parametros

### ISSUE THREAD

**Issue by joacir** [Matheusmelo3535/Estudos_TDD#10]
https://github.com/Matheusmelo3535/Estudos_TDD/blob/ff5a6ff4731a08780e70ba60a09450a9cc2eaac8/Testes/LutadorTest.php#L21

**Comment by Matheusmelo3535** [comment]
Adotei essa boa pratica, principalmente nos meus datas providers da classe test.

`public function lutadorDerrotasInvalidasProvider()
    {
        $nome = 'Robert Whittaker';
        $vitorias = '10';
        $derrotas = '-1';
        $rank = '9';
        $estatisticas = new EstatisticasLutador($vitorias, $derrotas, $rank);
        $lutador = new Lutador($nome, $estatisticas);

        return [
            'Lutador_DerrotasInvalidas' => [$lutador]
        ];
    }`
