### ISSUE TITLE
Faltou definir tipagem 

### ISSUE THREAD

**Issue by joacir** [Matheusmelo3535/Estudos_TDD#2]
https://github.com/Matheusmelo3535/Estudos_TDD/blob/ff5a6ff4731a08780e70ba60a09450a9cc2eaac8/src/Model/Lutador.php#L12

Importante definir um tipo, quando falamos de atributos de database.

**Comment by Matheusmelo3535** [comment]
`private string $nome;
    private EstatisticasLutador $estatisticas;
    private DateTime $created;
    private DateTime $modified;
    private DateTime $deleted;`

Todos os atributos estão tipados agora.
