### ISSUE TITLE
Utilizar constantes

### ISSUE THREAD

**Issue by joacir** [Matheusmelo3535/Estudos_TDD#3]
https://github.com/Matheusmelo3535/Estudos_TDD/blob/ff5a6ff4731a08780e70ba60a09450a9cc2eaac8/src/Model/Lutador.php#L53

Utilizar constantes para valores imútaveis

**Comment by Matheusmelo3535** [comment]
`const rankingsValidos = ['C','1','2','3','4','5','6','7','8','9','10'];`

Constante para rankings criada.
