### ISSUE TITLE
Muitos parâmetros nos métodos.

### ISSUE THREAD

**Issue by joacir** [Matheusmelo3535/Estudos_TDD#4]
https://github.com/Matheusmelo3535/Estudos_TDD/blob/ff5a6ff4731a08780e70ba60a09450a9cc2eaac8/src/Model/Lutador.php#L51

Sempre que ver mais de 2 parâmetros no método, optar por usar struct (array) ou uma classe.

**Comment by Matheusmelo3535** [comment]
Corrigido, optei por criar uma entidade(class) para representar as estatísticas , e fiz uma injeção de dependência no lutador.
