### ISSUE TITLE
Evite mais de 1 return por método.

### ISSUE THREAD

**Issue by joacir** [Matheusmelo3535/Estudos_TDD#5]
https://github.com/Matheusmelo3535/Estudos_TDD/blob/ff5a6ff4731a08780e70ba60a09450a9cc2eaac8/src/Model/Lutador.php#L55

Optar por guardar em variavel o retorno para ser usado no return final

Em caso de condição simples, o próprio condicional pode ser o return

**Comment by Matheusmelo3535** [comment]
Muito obrigado pela dica, em alguns casos utilizei uma variavel com o retorno booleano e em casos mais simples utilizei a propria condicional.
`public function validaNome(string $nomeLutador) 
    {
        return isset($nomeLutador) && strlen(trim($nomeLutador)) > 5;
    }`

`public function addLutador(Lutador $lutador)
    {
        $validacao = $this->validacaoAntesDeSalvar($lutador);
        if ($validacao){
            $dataCriacao = new DateTime('NOW');
            $dataCriacao->setTimezone(new DateTimeZone('America/Sao_Paulo'));
            $lutador->setCreated($dataCriacao);
        }
        return $validacao; 
    }`
