### ISSUE TITLE
Faltou tratamento da exception

### ISSUE THREAD

**Issue by joacir** [Matheusmelo3535/Estudos_TDD#6]
https://github.com/Matheusmelo3535/Estudos_TDD/blob/ff5a6ff4731a08780e70ba60a09450a9cc2eaac8/src/Model/Lutador.php#L86

Na verdade faltou também optar por usar ou não exceptions como conceito de validação. Pois em alguns pontos tem geração de exception e em outros tem return bool. (Faltou coesão)

Se for optar por Exceptions também é preciso tratamento das exceptions (try .. catch)

**Comment by Matheusmelo3535** [comment]
Corrigido, optei por usar retornos booleanos, as exceptions estavam no código apenas para estudar a criação de testes em cima de exceptions.
