### ISSUE TITLE
Sempre usar o tearDown pra "limpar"

### ISSUE THREAD

**Issue by joacir** [Matheusmelo3535/Estudos_TDD#8]
https://github.com/Matheusmelo3535/Estudos_TDD/blob/ff5a6ff4731a08780e70ba60a09450a9cc2eaac8/Testes/LutadorTest.php#L12

**Comment by Matheusmelo3535** [comment]
`public function tearDown(): void
    {
        unset($this->crud);
    }`

Agora estou utilizando o UNSET para o garbage collector fazer o serviço dele, obrigado pela dica!
