### ISSUE TITLE
Optar por usar this inves de self

### ISSUE THREAD

**Issue by joacir** [Matheusmelo3535/Estudos_TDD#9]
https://github.com/Matheusmelo3535/Estudos_TDD/blob/ff5a6ff4731a08780e70ba60a09450a9cc2eaac8/Testes/LutadorTest.php#L23

Optar por $this->asserts...

**Comment by Matheusmelo3535** [comment]
Ficava em dúvida entre utilizar static,self ou $this, agradeço a dica! Estou utilizando apenas o $this agora, para facilitar o entendimento do código.

`public function testAdicionarLutadorComOsDadosValidos(Lutador $lutador)
    {

        $this->assertEquals(true, $this->crud->addLutador($lutador));
        $this->assertEquals('Matheuszera', $lutador->getNome());
    }`
